version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - export ECR_REPOSITORY_URI=971937583465.dkr.ecr.us-west-1.amazonaws.com/python-ml:latest
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export DOCKER_BUILDKIT=0
      - docker build -t python-ml .
      - docker tag python-ml $ECR_REPOSITORY_URI

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI
      - printf '[{"name":"python-ml","imageUri"}]' $ECR_REPOSITORY_URI > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Updating Lambda function to use the latest image...
      - aws lambda update-function-code --function-name TicTacToeLambda --image-uri $ECR_REPOSITORY_URI --region $AWS_DEFAULT_REGION
      - echo Build completed on `date`






