version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      # Ensure ECR_REPOSITORY_URI is set to repo only, without tag
      - export ECR_REPOSITORY_URI=971937583465.dkr.ecr.us-west-1.amazonaws.com/python-ml
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - export DOCKER_BUILDKIT=0
      - docker build -t python-ml .
      - docker tag python-ml $ECR_REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URI:latest
      # Use imagedefinitions.json for CodePipeline ECS/Lambda deploy
      - printf '[{"name":"python-ml","imageUri":"%s:latest"}]' $ECR_REPOSITORY_URI > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed on `date`

artifacts:
  files:
    - imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed on `date`

artifacts:
  files:
    - imagedefinitions.json
